Patch
alberthli/mujoco_mpc pull request #7
Opened 2024-01-19 18:41 UTC by thowell

2024-01-19 18:59 UTC, alberthli requested changes
besides stray file, lgtm

2024-01-19 18:59 UTC, alberthli commented on right_hand.xml.patch
Stray empty file?

2024-01-20 17:41 UTC, thowell commented on right_hand.xml.patch
Good catch!

2024-01-20 21:11 UTC, alberthli approved these changes
nice catch on not loading the modified model into `task.xml`. lgtm.

2024-01-20 21:11 UTC, merged